#%RAML 1.0 NamedExample
value:
  senderName: ShikunTest
  sendId: SummerSale2025
  subscribers: "050-1112233,0501112244,+972501112255"
  message: "Dear customer, check out our new projects at shikun.co.il"
